image:
  ## Name of the image you want to build/deploy
  ## Defaults to the release name
  name: quay.io/qiotmanufacturing/factory-production-validator
  ## Tag that you want to build/deploy
  tag: latest 

build:
  enabled: false

deploy:
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

  serviceType: ClusterIP

  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  route:
    enabled: true
    targetPort: http
    tls:
      enabled: true
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
      ## IMPORTANT: Do not check 'key' into git!
      key:
      caCertificate:
      certificate:
      destinationCACertificate:
  livenessProbe:
    tcpSocket:
      port: http
  readinessProbe:
    httpGet:
      path: /q/health/ready
      port: http

  applicationProperties:
    enabled: true
    #jvm
    #mountPath:  /deployments/config
    #s2i
    #mountPath:  /home/quarkus/config
    #JKube
    mountPath:  /config
    properties: |-
      ## Properties go here
      quarkus.kubernetes-client.namespace=manufacturing-dev
      quarkus.http.port=8080
      registration-service-api/mp-rest/url=http://registration-service:8080
      quarkus.datasource.jdbc.url=jdbc:postgresql://sqlstorage-service:5432/qiot_manufacturing
      quarkus.ssl.native=false
      quarkus.native.enable-all-security-services=false
      factoryproductline-api/mp-rest/url=http://product-line-service:8080
      facility-manager-api/mp-rest/url=http://facility-manager-service:8080
      kafka.bootstrap.servers=datacenter.local:9092
      quarkus.artemis.url=tcp://broker-service:61616


